version: "3.9"

services:
  mariadb:
    image: mariadb:11.3
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: escape_musee
    ports:
      - "3307:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: .
    container_name: voyage_backend
    restart: always
    ports:
      - "4000:4000"
#    depends_on:
#      mariadb:
#        condition: service_healthy
    env_file:
      - ./.env
    volumes:
      - ./:/app
    command: npm start

volumes:
  mariadb_data:
